version: '3'
services:
  db:
    image: mongo
    ports:
      - '27017:27017'
  server:
    build: ./server
    ports:
      - '5000:5000'
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server